# Site settings
title: Egret产品文档
email: your-email@domain.com
description: "Egret产品文档,HTML5游戏引擎"
baseurl: ""
url: "/home.html"

# Build settings
#markdown: kramdown
markdown: redcarpet
permalink: pretty
encoding: utf-8
safe: false

#pygments: true
highlighter: pygments


#菜单配置
nav:
  - text: 回到官网
    url: http://www.egret-labs.org
  - text: 文档
    url: /home.html
  - text: API文档
    url: /api/api.html
#  - text: Flash移植教程
#    url: /flash.html
  - text: AS3对比参考
    url: /as2ts/index.html
  - text: FAQ
    url: /faq.html

#文档一级分类
docsType:
  - text: 快速入门
    grid: 3
    type: quitestart
  - text: 开发指南
    grid: 3
    type: manual
  - text: 演示实例
    type: demo
    grid: 4
  - text: 开发工具
    type: tools
    grid: 3

#文档二级分了
quitestart:
  - text: 1、简介
    enter: true
    element: quitestartabout
    url: post/quitestart/about/aboutegret.html
    des: Egret引擎以及相关产品介绍。
  - text: 2、安装与部署
    element: quitestartinstall
    url: post/quitestart/install/installwin.html
    des: Egret引擎安装文档说明。
  - text: 3、Hello World
    fenter: false
    element: quitestarthelloworld
    url: post/quitestart/helloworld/helloworld.html
    des: 使用Egret创建你的第一个游戏。

manual:
  - text: 视觉编程
    element: manualdisplay
    url: post/manual/display/aboutdisplay.html
    des: 详细介绍了Egret中显示对象的架构设计以及一些概念
    enter: true

  - text: 显示对象
    element: manualdisplayobj
    url: post/manual/displayobj/aboutdisplayobj.html
    des: 详细介绍了Egret中显示对象的基础知识以及使用方法

  - text: 显示容器
    element: manualdisplaycon
    url: post/manual/displaycon/aboutdisplaycon.html
    des: 详细介绍了显示容器以及显示列表的使用方法
    fenter: false

  - text: 事件机制
    element: manualevent
    url: post/manual/event/useevent.html
    des: 介绍了Egret中的事件机制以及详细的使用方法。
    enter: true

  - text: RES资源加载
    element: manualloader
    url: post/manual/loader/res.html
    des: 介绍Egret引擎中相关资源加载方面的内容。

  - text: 位图纹理
    element: manualtexture
    url: post/manual/bitmap/createbitmap.html
    des: 位图和纹理相关的使用方法
    fenter: false

  - text: 矢量绘图
    element: manualgraphics
    url: post/manual/graphics/drawrect.html
    des: 关于绘图API的使用方法与技巧。
    enter: true

  - text: GUI
    element: manualgui
    url: post/manual/other/gui1.html
    des: 这部分内容介绍了Egret中的GUI模块设计思想以及使用方法。

  - text: 文本
    element: manualtext
    url: post/manual/text/createtext.html
    des: 关于Egret中相关文本的使用方法。
    fenter: false

  - text: 动画
    element: manualmoive
    url: post/manual/anim/tween.html
    des: 介绍了Egret中多种动画方案的使用方法。
    enter: true

  - text: 计时器
    url: post/manual/timer/timer.html
    des: 介绍了Egret中关于计时器的使用方法。
    element: manualtime

  - text: 声音
    element: manualsound
    url: post/manual/sound/aboutsound.html
    des: Egret中的音频系统功能介绍，详细介绍了音频的加载、播放、暂停以及调节音量等功能。
    fenter: false

  - text: 网络
    element: manualnetwork
    url: post/manual/net/createconnect.html
    des: egret中相关的网络操作。例如，加载数据，服务器通讯等。
    enter: true

  - text: 调试
    element: manualdebug
    url: post/manual/debug/chromedebug.html
    des: 详细介绍了Egret可以使用的调试工具与调试技巧。

  - text: 移动APP打包
    element: manualnative
    url: post/tools/native/androidforwindows.html
    des: 详细介绍了iOS，Android和Windows Phone平台的APP打包解决方案是打包方法。
    fenter: false

# - text: 打包发布
#   element: manualpublish
#   url: #
#   des: 编辑努力码字中...

# - text: 高级开发
#   element: manualother
#   url: post/manual/other/gui1.html
#   des: 一些关于Egret引擎的高级知识，涉及到引擎的架构和一些模块的设计思想。同时还包含一些高级应用文档。



demo:
  - text: 基础
    enter: true
    element: demobasics
#    url: demo/helloworldbasic.html
  - text: 显示对象
    element: demodisplay
#    url: demo/display.html
  - text: 事件
    element: demoevent
#    url: demo/event.html
#  - text: 布局
#    fenter: false
#    element: demolayout
#    url: demo/layout.html
  - text: 声音
    fenter: false
    element: demosound
#    des: 编辑努力码字中...
#    url: demo/sound.html
  - text: 网络
    enter: true
    element: demonetwork
#    url: demo/network.html
  - text: 文本
    element: demotext
#    url: demo/text.html
  - text: 动画
    element: demomovie
#    url: demo/movie.html
  - text: GUI
    fenter: false
    element: demogui
    des: 编辑努力码字中...
#    url: demo/gui.html
#  - text: 高级
#    fenter: false
#    element: demoother
#    url: demo/other.html

tools:
  - text: 官方工具
    enter: true
    element: egrettools
#    url: post/tools/egrettools/conversiontool.html
  - text: 官方插件
    element: egretplugin
    des: 编辑努力码字中...
#    url: post/tools/egretplugin/index.html
  - text: 代码编辑器
    fenter: false
    element: ide
#    url: post/tools/ide/webstorm.html
  - text: 第三方工具
    enter: true
    element: othertools
#    url: post/tools/othertools/texturepacker.html
  - text: 服务器工具
    element: servertools
#    url: post/tools/servertools/xampp.html
  - text: 浏览器工具
    fenter: false
    element: browsertools
#    url: post/tools/browser/chrome.html

#AS3 TS代码对比参考目录 及参数
codePageTitle: Flash ActionScript 3代码迁移Egret在线参考
codeType:
  - text: 显示列表
    type: codedisplay
    uiid: collapseOne
  - text: 网络
    type: codenetwork
    uiid: collapseTwo
  - text: 事件处理
    type: codeevent
    uiid: collapseThree
  - text: WebGL
    type: codewebgl
    uiid: collapseFour
  - text: 文本
    type: codetext
    uiid: collapseFive
  - text: 动画
    type: codeanm
    uiid: collapseSix
  - text: 通用
    type: codeother
    uiid: collapseSeven

