# Site settings
title: Egret产品文档
email: your-email@domain.com
description: "Egret产品文档,HTML5游戏引擎"
baseurl: ""
url: "/home.html"

# Build settings
#markdown: kramdown
markdown: redcarpet
permalink: pretty
encoding: utf-8
safe: false

#pygments: true
highlighter: pygments


#菜单配置
nav:
  - text: 回到官网
    url: http://www.egret-labs.org
  - text: 文档
    url: /home.html

  - text: 专题讲解
    url: /subj/index.html

  - text: API文档
    url: /api/api.html
#  - text: Flash移植教程
#    url: /flash.html
  - text: AS3对比参考
    url: /as2ts/index.html

  - text: FAQ
    url: /faq.html

#文档一级分类
docsType:
  - text: 快速入门
    grid: 3
    type: quitestart
  - text: 开发指南
    grid: 3
    type: manual
  - text: GUI开发指南
    grid: 3
    type: guimanual
  - text: 平台/广告接入
    grid: 3
    type: platform
  - text: 演示实例
    type: demo
    grid: 4
  - text: 开发工具
    type: tools
    grid: 3

#文档二级分了
quitestart:
  - text: 1、简介
    enter: true
    element: quitestartabout
    url: post/quitestart/about/aboutegret.html
    des: Egret引擎以及相关产品介绍。
  - text: 2、安装与部署
    element: quitestartinstall
    url: post/quitestart/install/installwin.html
    des: Egret引擎安装文档说明。
  - text: 3、Hello World
    fenter: false
    element: quitestarthelloworld
    url: post/quitestart/helloworld/helloworld.html
    des: 使用Egret创建你的第一个游戏。

manual:
  - text: 视觉编程
    element: manualdisplay
    url: post/manual/display/aboutdisplay.html
    des: 详细介绍了Egret中显示对象的架构设计以及一些概念，还有脏矩形的用法。
    enter: true

  - text: 显示对象
    element: manualdisplayobj
    url: post/manual/displayobj/aboutdisplayobj.html
    des: 详细介绍了Egret中显示对象的基础知识以及使用方法。

  - text: 显示容器
    element: manualdisplaycon
    url: post/manual/displaycon/aboutdisplaycon.html
    des: 详细介绍了显示容器以及显示列表的使用方法。
    fenter: false

  - text: 事件机制
    element: manualevent
    url: post/manual/event/useevent.html
    des: 介绍了Egret中的事件机制以及详细的使用方法。
    enter: true

  - text: RES资源加载
    element: manualloader
    url: post/manual/loader/res.html
    des: 介绍Egret引擎中相关资源加载方面的内容。

  - text: 位图纹理
    element: manualtexture
    url: post/manual/bitmap/createbitmap.html
    des: 位图和纹理相关的使用方法。
    fenter: false

  - text: 矢量绘图
    element: manualgraphics
    url: post/manual/graphics/drawrect.html
    des: 关于绘图API的使用方法与技巧。
    enter: true

  - text: 文本
    element: manualtext
    url: post/manual/text/createtext.html
    des: 关于Egret中相关文本的使用方法。
    

  - text: 动画
    element: manualmoive
    url: post/manual/anim/tween.html
    des: 介绍了Egret中多种动画方案的使用方法。
    fenter: false

  - text: 计时器
    url: post/manual/timer/timer.html
    des: 介绍了Egret中关于计时器的使用方法。
    element: manualtime
    enter: true

  - text: 声音
    element: manualsound
    url: post/manual/sound/aboutsound.html
    des: Egret中的音频系统功能介绍，详细介绍了音频的加载、播放、暂停以及调节音量等功能。

  - text: 网络
    element: manualnetwork
    url: post/manual/net/createconnect.html
    des: egret中相关的网络操作。例如，加载数据，服务器通讯以及方便的WebSocket等功能。
    fenter: false

  - text: 开发工具配置
    element: manualdebug
    url: post/manual/debug/chromedebug.html
    des: 详细介绍了Egret可以使用的开发工具与相关工具的配置方法。
    enter: true

  - text: 移动APP打包
    element: manualnative
    url: post/tools/native/androidforwindows.html
    des: 详细介绍了iOS，Android和Windows Phone平台的APP打包解决方案是打包方法。
    
  - text: 第三方库
    element: threelibs
    url: post/manual/threelibs/uselibs.html
    des: 详细介绍了Egret中第三方库的使用。
    fenter: false

  - text: 粒子系统
    element: particle
    url: post/manual/particle/aboutparticle.html
    des: 详细介绍了Egret中粒子库的使用于扩展方法。
    enter: true 

  - text: 适配策略
    element: adaptive
    url: post/manual/adaptive/screenadaptive.html
    des: 介绍Egret在不同设备中的一些适配策略。
    fenter: true

  - text:  物理引擎
    element: manual-physical-engine
    url: jkdoc/manual-physical-engine.html
    des: 介绍可以打造超酷物理效果的物理引擎。
    fenter: false

  - text: 命令行大全
    element: cmd-set
    url: jkdoc/manual-cmd-intro.html
    des: 详细介绍了Egret中主要的控制台命令的用法。
    enter: true 

  - text: 性能基准测试
    element: benchmark
    url: jkdoc/benchmark-bitmap.html
    des: 对Egret开发的各种场景进行性能基准测试，每个基准针对一项功能。便于开发者在特定机型下进行性能瓶颈分析。
    fenter: true

  - text: 开发实践性能优化
    element: optimizingPerformance
    url: jkdoc/optimizing-performance-for-the-egret-platform1.html
    des: 对Egret开发中遇到的一些性能问题进行分析与说明，最大程度优化游戏性能。
    fenter: false

guimanual:
  - text: 关于GUI库
    enter: true
    element: aboutgui
    url: post/guimanual/aboutgui/aboutguilib.html
    des: GUI库学习导读,GUI入门必读指南。

  - text: 控件的使用
    element: usecontrol
    des: 所谓控件，主要是相对容器而言，实现某一个特定功能。
    url: post/guimanual/usecontrol/uselabel.html

  - text: 容器
    fenter: false
    element: container
    des: 容器本身也是显示对象，但区别在于，容器可以放其他的显示对象。
    url: post/guimanual/container/group.html

  - text: 数据集合
    enter: true
    element: guidata
    des: 本章介绍典型的组件+数据的分离方式。
    url: post/guimanual/guidata/arraycollection.html

  - text: 窗体
    element: window
    des: 本章节讲解窗体的用法和PopUp机制。
    url: post/guimanual/window/titlewindow.html

  - text: 导航
    fenter: false
    element: navigator
    des: 讲解导航容器或组件的用法。
    url: post/guimanual/navigator/viewstack.html

  - text: 布局和定位
    enter: true
    element: layout
    des: 本章节讲解组件如何布局。
    url: post/guimanual/layout/defaultlayout.html

  - text: 视图状态
    element: stategui
    des: 本章节讲解关于试图状态的使用。
    url: post/guimanual/stategui/stateview.html

  - text: 皮肤机制
    fenter: false
    element: skingui
    des: 讲解GUI的皮肤机制。
    url: post/guimanual/skingui/skinadapter.html

  - text: GUI框架解读
    enter: true
    element: designgui
    des: GUI框架底层原理解析。
    url: post/manual/other/gui1.html

  - text: Egret Wing
    fenter: false
    element: wing
    des: Egret Wing使用手册
    url: post/guimanual/wing/aboutwing.html



platform:
  - text: 广告接入
    enter: true
    element: adAccess
  - text: 平台接入
    element: platformAccess
  - text: Native SDK接入
    fenter: false
    element: sdkAccess


demo:
  - text: 基础
    enter: true
    element: demobasics
#    url: demo/helloworldbasic.html
  - text: 显示对象
    element: demodisplay
#    url: demo/display.html
  - text: 事件
    element: demoevent
#    url: demo/event.html
#  - text: 布局
#    fenter: false
#    element: demolayout
#    url: demo/layout.html
  - text: 声音
    fenter: false
    element: demosound
#    des: 编辑努力码字中...
#    url: demo/sound.html
  - text: 网络
    enter: true
    element: demonetwork
#    url: demo/network.html
  - text: 文本
    element: demotext
#    url: demo/text.html
  - text: 动画
    element: demomovie

#    url: demo/movie.html
#  - text: GUI
    fenter: false

tools:
  - text: 官方工具
    enter: true
    element: egrettools
#    url: post/tools/egrettools/conversiontool.html

  - text: 官方插件
    element: egretplugin
#    des: Comming Soon...
#    url: jkdoc/tools-plugin-inspector.html

  - text: 代码编辑器
    fenter: false
    element: ide
#    url: post/tools/ide/webstorm.html

  - text: 第三方工具
    enter: true
    element: othertools
#    url: jkdoc/tools-othertools-dragonbones.html

  - text: 服务器工具
    element: servertools
#    url: post/tools/servertools/xamanualnetworkmpp.html

  - text: 浏览器工具
    fenter: false
    element: browsertools
#    url: post/tools/browser/chrome.html


#subj类目文件
subjPageTitle: Egret开发专题讲解
subjType:
  - text: 通用
    type: proj-normal
    uiid: proj-normal

#AS3 TS代码对比参考目录 及参数
codePageTitle: Flash ActionScript 3代码迁移Egret在线参考
codeType:
  - text: 显示列表
    type: codedisplay
    uiid: collapseOne
  - text: 网络
    type: codenetwork
    uiid: collapseTwo
  - text: 事件处理
    type: codeevent
    uiid: collapseThree
  - text: WebGL
    type: codewebgl
    uiid: collapseFour
  - text: 文本
    type: codetext
    uiid: collapseFive
  - text: 动画
    type: codeanm
    uiid: collapseSix
  - text: 通用
    type: codeother
    uiid: collapseSeven

